STUDENT_QUESTIONS = [
  "Qual é o visto de estudante necessário para estudar na Austrália?",
  "Como faço para solicitar um visto de estudante australiano?",
  "Qual é o processo de aplicação para um visto de estudante australiano?",
  "Quais são os requisitos para a obtenção de um visto de estudante australiano?",
  "Quais documentos são necessários para solicitar um visto de estudante australiano?",
  "Quanto tempo leva para processar um visto de estudante australiano?",
  "É possível trabalhar enquanto estudo com um visto de estudante australiano?",
  "Quais são as restrições de trabalho com um visto de estudante australiano?",
  "Posso renovar meu visto de estudante australiano?",
  "Quais são as taxas associadas ao visto de estudante australiano?",
  "Posso trazer minha família para a Austrália comigo com um visto de estudante?",
  "Quais são os requisitos financeiros para um visto de estudante australiano?",
  "Preciso de um seguro de saúde para solicitar um visto de estudante australiano?",
  "Como faço para encontrar acomodação enquanto estudo na Austrália?",
  "É necessário fazer um exame médico para solicitar um visto de estudante australiano?",
  "Quais são as restrições de viagem com um visto de estudante australiano?",
  "Posso viajar para fora da Austrália com um visto de estudante australiano?",
  "O que acontece se eu não seguir as regras do meu visto de estudante australiano?",
  "Quanto tempo posso permanecer na Austrália com um visto de estudante australiano?",
  "Posso mudar de curso ou instituição enquanto estudo com um visto de estudante australiano?",
  "Preciso de um agente de imigração para me ajudar com o meu visto de estudante australiano?",
  "O que acontece se meu visto de estudante australiano for negado?",
  "Como faço para renovar meu visto de estudante australiano?",
  "Qual é a diferença entre um visto de estudante e um visto de trabalho na Austrália?",
  "Posso aplicar para um visto de estudante australiano se eu já tiver sido deportado da Austrália antes?"
]